---
- hosts: all
  become: yes
  tasks:
   - name: Install Ngix server!
     yum: name=httpd state=installed update_cache=true
     notify:
      - start -nginx
  handlers:
   - name: start nginx
     service: name=httpd state=started     

